### import modules

In [1]:
import lightgbm as lgb

import numpy as np
import pandas as pd
from sklearn.model_selection import KFold, train_test_split, ParameterGrid
from sklearn.metrics import confusion_matrix, mean_squared_error, f1_score
from sklearn.datasets import load_iris, load_digits, load_boston

import warnings
warnings.filterwarnings('ignore')

rng = np.random.RandomState(950530)
lgb.__version__

'3.1.1'

In [ ]:
boston = load_boston()
y = boston['target']
X = boston['data']

In [41]:
import lightgbm as lgb
from sklearn.model_selection import train_test_split
X_train, X_valid, y_train, y_valid = train_test_split(X, y)
lgb_model = lgb.LGBMRegressor(early_stopping_round = 20, metric = 'mse')
lgb_model.fit(X_train, y_train,
             eval_set = [(X_valid, y_valid)]) # NEEDS

predictions = lgb_model.predict(X_valid)
actuals = y_valid

print(mean_squared_error(actuals, predictions))

[1]	valid_0's l2: 0.613545
Training until validation scores don't improve for 20 rounds
[2]	valid_0's l2: 0.508422
[3]	valid_0's l2: 0.424955
[4]	valid_0's l2: 0.352433
[5]	valid_0's l2: 0.299748
[6]	valid_0's l2: 0.253002
[7]	valid_0's l2: 0.220251
[8]	valid_0's l2: 0.190313
[9]	valid_0's l2: 0.166706
[10]	valid_0's l2: 0.144424
[11]	valid_0's l2: 0.129655
[12]	valid_0's l2: 0.115111
[13]	valid_0's l2: 0.105544
[14]	valid_0's l2: 0.0980449
[15]	valid_0's l2: 0.0914526
[16]	valid_0's l2: 0.0864362
[17]	valid_0's l2: 0.0829129
[18]	valid_0's l2: 0.0805249
[19]	valid_0's l2: 0.0783062
[20]	valid_0's l2: 0.0764294
[21]	valid_0's l2: 0.07496
[22]	valid_0's l2: 0.0738617
[23]	valid_0's l2: 0.073135
[24]	valid_0's l2: 0.072555
[25]	valid_0's l2: 0.0721883
[26]	valid_0's l2: 0.0719173
[27]	valid_0's l2: 0.0724773
[28]	valid_0's l2: 0.0730644
[29]	valid_0's l2: 0.072905
[30]	valid_0's l2: 0.0728819
[31]	valid_0's l2: 0.0735359
[32]	valid_0's l2: 0.0735193
[33]	valid_0's l2: 0.0735403
[34]	vali

In [2]:
iris = load_iris()
y = iris['target']
X = iris['data']
kf = KFold(n_splits=2, shuffle=True, random_state=rng)

In [31]:
import lightgbm as lgb
from sklearn.model_selection import train_test_split
X_train, X_valid, y_train, y_valid = train_test_split(X, y)
lgb_model = lgb.LGBMClassifier(early_stopping_round = 20, metric = 'multi_logloss')
lgb_model.fit(X_train, y_train,
             eval_set = [(X_valid, y_valid)]) # NEEDS

print(confusion_matrix(actuals, predictions))

[1]	valid_0's multi_logloss: 0.987072
Training until validation scores don't improve for 20 rounds
[2]	valid_0's multi_logloss: 0.89091
[3]	valid_0's multi_logloss: 0.782331
[4]	valid_0's multi_logloss: 0.688993
[5]	valid_0's multi_logloss: 0.611978
[6]	valid_0's multi_logloss: 0.551269
[7]	valid_0's multi_logloss: 0.493302
[8]	valid_0's multi_logloss: 0.450718
[9]	valid_0's multi_logloss: 0.404287
[10]	valid_0's multi_logloss: 0.371764
[11]	valid_0's multi_logloss: 0.336915
[12]	valid_0's multi_logloss: 0.309117
[13]	valid_0's multi_logloss: 0.290616
[14]	valid_0's multi_logloss: 0.265338
[15]	valid_0's multi_logloss: 0.247972
[16]	valid_0's multi_logloss: 0.230982
[17]	valid_0's multi_logloss: 0.21855
[18]	valid_0's multi_logloss: 0.207123
[19]	valid_0's multi_logloss: 0.197597
[20]	valid_0's multi_logloss: 0.189474
[21]	valid_0's multi_logloss: 0.181595
[22]	valid_0's multi_logloss: 0.176537
[23]	valid_0's multi_logloss: 0.167184
[24]	valid_0's multi_logloss: 0.164225
[25]	valid_0's

In [ ]:
boston = load_boston()
y = boston['target']
X = boston['data']

In [24]:
for train_index, test_index in kf.split(X):
    X_train, y_train = X[train_index], y[train_index]
    X_valid, y_valid = X[test_index] , y[test_index]
    lgb_model = lgb.LGBMClassifier(early_stopping_round = 20, metric = 'multi_logloss')
    lgb_model.fit(X_train, y_train,
                 eval_set = [(X_valid, y_valid)])
    print()

[1]	valid_0's multi_logloss: 0.95551
Training until validation scores don't improve for 20 rounds
[2]	valid_0's multi_logloss: 0.816281
[3]	valid_0's multi_logloss: 0.708683
[4]	valid_0's multi_logloss: 0.620288
[5]	valid_0's multi_logloss: 0.546995
[6]	valid_0's multi_logloss: 0.483309
[7]	valid_0's multi_logloss: 0.432137
[8]	valid_0's multi_logloss: 0.385391
[9]	valid_0's multi_logloss: 0.348436
[10]	valid_0's multi_logloss: 0.320539
[11]	valid_0's multi_logloss: 0.294368
[12]	valid_0's multi_logloss: 0.268866
[13]	valid_0's multi_logloss: 0.247843
[14]	valid_0's multi_logloss: 0.229687
[15]	valid_0's multi_logloss: 0.21402
[16]	valid_0's multi_logloss: 0.20124
[17]	valid_0's multi_logloss: 0.186713
[18]	valid_0's multi_logloss: 0.176332
[19]	valid_0's multi_logloss: 0.166914
[20]	valid_0's multi_logloss: 0.159202
[21]	valid_0's multi_logloss: 0.153756
[22]	valid_0's multi_logloss: 0.146985
[23]	valid_0's multi_logloss: 0.142102
[24]	valid_0's multi_logloss: 0.137605
[25]	valid_0's 

### 파라미터 정리
**파라미터 참고문서**
- [lightGBM parameters](https://lightgbm.readthedocs.io/en/latest/Parameters.html#objective)
- [Laura++](https://sites.google.com/view/lauraepp/parameters)

In [101]:
#### 파라미터 ####

# 최대 깊이
max_depth = -1

# 하나의 Leaf가 가지고 있는 최소한의 관측치 수
min_data_in_leaf = 20

# column sampling ratio
feature_fraction = 1 # .7 (typically)

# row sampling ratio
bagging_fraction = 1 # .7 (typically)

# ratio of L1, L2 regularization
lambda_l1 = 0
lambda_l2 = 0

# 범주형 변수가 있는 경우, 범주의 최대 개수 설정
max_cat_threshold = 32

# 
early_stopping_round = 'NULL'




#### Core parameter ####
#### ############## ####

task = 'train'
#  'train'         , for training, 
#  'predict'       , for prediction, 
#  'convert_model' , for converting model file into if-else format, see more information in Convert Parameters
#  'refit'         , for refitting existing models with new data, aliases: refit_tree
#  'save_binary'   , load train (and validation) data then save dataset to binary file. Typical usage: save_binary first, then run multiple train tasks in parallel using the saved binary file
# Note: can be used only in CLI version; for language-specific packages you can use the correspondent functions

boosting = 'gdbt'
#  'gbdt' , traditional Gradient Boosting Decision Tree, aliases: gbrt
#  'rf'   , Random Forest, aliases: random_forest
#  'dart' , Dropouts meet Multiple Additive Regression Trees
#  'goss' , Gradient-based One-Side Sampling
# Note: internally, LightGBM uses gbdt mode for the first 1 / learning_rate iterations

application = 'regression'
# objective
# Go README.md

num_iterations = 100 
# typically n_iter >= 100
# number of boosting iterations

learning_rate = 0.1 
# typically 0.1, 0.001, 0.0003
# Go README.md

num_leaves = 31 
# max number of leaves in one tree



#### Metric parameters ####
#### ################# ####

metric = ''
# 'mean_absolute_error',     MAE
# 'mean_squared_error',      MSE
# 'root_mean_squared_error', RMSE
# 'binary_logloss'
# 'multi_logloss'
# For more detail, Go README.md


#### I/O parameters ####
#### ############# ####

max_bin = 32

categorical_feature = ''
# 범주형 변수의 index를 기입
# categorical_feature = 0,1,2
# categorical_feature = name: C0, C1, C2

ignore_column = ''
# 학습에서 무시할 변수 선택
# 위와 동일한 방법 사용



PARAMETERS = {
    'max_depth' : max_depth,
    'min_data_in_leaf' : min_data_in_leaf,
    'feature_fraction' : feature_fraction,
    'bagging_fraction' : bagging_fraction,
    'early_stopping_round' : early_stopping_round,
    'lambda_l1' : lambda_l1,
    'lambda_l2' : lambda_l2,
    'max_cat_threshold' : max_cat_threshold,
    
    'task' : task,
    'boosting' : boosting,
    'application' : application,
    'num_iterations' : num_iterations,
    'learning_rate' : learning_rate,
    
    'metric' : metric,
    
    'max_bin' : max_bin,
    'categorical_feature' : categorical_feature,
    'ignore_column' : ignore_column

}

In [102]:
for train_index, test_index in kf.split(X):
    
    lgb_model = lgb.LGBMClassifier(**parameters)
    lgb_model.fit(X[train_index], y[train_index])
    predictions = lgb_model.predict(X[train_index])
    actuals = y[test_index]
    print(confusion_matrix(actuals, predictions))

[[21  0  0]
 [ 8 18  0]
 [ 0  6 22]]
[[21  8  0]
 [ 0 18  6]
 [ 0  0 22]]
