In [1]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [61]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("Vectorized version:"+str(1000*(toc-tic))+"ms")


c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print("For loop:"+str(1000*(toc-tic))+"ms")

249974.16495390478
Vectorized version:0.8320808410644531ms
249974.16495390175
For loop:447.04699516296387ms


In [63]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
            [1.2, 104.0, 52, 8],
            [1.8, 135, 99, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [64]:
cal = A.sum(axis = 0)
print(cal)

[ 59.  239.  155.4  76.9]


In [65]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [66]:
cal.reshape(1,4)

array([[ 59. , 239. , 155.4,  76.9]])

In [67]:
import numpy as py

a = np.random.randn(5)
print(a)

[ 0.19560162 -0.42802204  0.50914938  0.04542045  1.3648383 ]


In [68]:
print(a.shape)

(5,)


In [69]:
print(a.T)

[ 0.19560162 -0.42802204  0.50914938  0.04542045  1.3648383 ]


In [70]:
print(np.dot(a, a.T))

2.345542567488829


In [73]:
a = np.random.randn(5,1)
print(a)

[[-0.41848262]
 [ 0.22661616]
 [-0.78168496]
 [ 0.58507659]
 [-0.72096054]]


In [74]:
print(a.T)

[[-0.41848262  0.22661616 -0.78168496  0.58507659 -0.72096054]]


In [76]:
print(np.dot(a, a.T))

[[ 0.1751277  -0.09483492  0.32712157 -0.24484438  0.30170945]
 [-0.09483492  0.05135489 -0.17714244  0.13258781 -0.16338131]
 [ 0.32712157 -0.17714244  0.61103137 -0.45734557  0.56356401]
 [-0.24484438  0.13258781 -0.45734557  0.34231461 -0.42181713]
 [ 0.30170945 -0.16338131  0.56356401 -0.42181713  0.5197841 ]]


In [77]:
a = np.random.randn(4, 3) 
b = np.random.randn(3, 2)
a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [79]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b 
print(c)

[[ 4.36873205e-01  4.25172496e-01  8.98440246e-01]
 [-8.73427573e-05 -9.44343755e-02 -2.86084570e-01]
 [ 7.66817891e-01 -1.15852998e+00 -1.60188163e+00]]
